### ISSUE TITLE
Suggestion: Comments and Coding Conventions

### ISSUE THREAD

**Issue by marhyorh** [FreeCodeCampLagos/website#1]
1. Comments allows users to easily understand your codes.
2. Code Conventions help improve the readability of codes and make software maintenance easier.

Let's make it a habit of placing comments on codes that are served to multiple users for the reason stated above.

I suggest these docs for code convention; https://github.com/freecodecamp/freecodecamp/wiki/free-code-camp-javascript-style-guide and https://github.com/airbnb/javascript/tree/master/es5

**Comment by mabogunje** [comment]
I approve! Will update the README to reflect this.

**Comment by mabogunje** [comment]
Updated! See README.md
